name: MSVC-Analysis

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  build: '${{ github.workspace }}/build'
  result: '${{ github.workspace }}/build/results.sarif'

jobs:
  build:
    name: Run Analysis
    runs-on: windows-latest

    steps:
    - name: Checkout action
      uses: actions/checkout@v2.3.4

    - name: Initialize sample CMake Project
      uses: lukka/run-cmake@v3
      with:
        cmakeListsTxtPath: ${{ github.workspace }}/CMakeLists.txt
        buildDirectory: ${{ env.build }}
        cmakeGenerator: VS16Win64
        buildWithCMake: false
      
    - name: Run action
      id: run_action
      continue-on-error: true
      uses: microsoft/msvc-code-analysis-action@main
      with:
        cmakeBuildDirectory: ${{ env.build }}
        ruleset: All.ruleset
        ignoreSystemHeaders: true

    - name: Upload SARIF to Github
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: ${{ steps.run-analysis.outputs.sarif }}

    - name: Upload SARIF as an Artifact
      uses: actions/upload-artifact@v2
      with:
        name: sarif-file
        path: ${{ steps.run-analysis.outputs.sarif }}