name: MSVC-Analysis

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  build: '${{ github.workspace }}/build'
  config: 'Debug'
  result: '${{ github.workspace }}/build/results.sarif'

jobs:
  analyze:
    name: Analyze
    runs-on: windows-latest

    steps:
    - name: Checkout action
      uses: actions/checkout@v2.3.4

    - name: Configure CMake
      run: cmake -B ${{ env.build }} -DCMAKE_BUILD_TYPE=${{ env.config }}
      
    - name: Run Analysis
      uses: microsoft/msvc-code-analysis-action@main
      id: run-analysis
      with:
        cmakeBuildDirectory: ${{ env.build }}
        buildConfiguration: ${{ env.config }}
        ruleset: All.ruleset

    - name: Upload SARIF to Github
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: ${{ steps.run-analysis.outputs.sarif }}

    - name: Upload SARIF as an Artifact
      uses: actions/upload-artifact@v2
      with:
        name: sarif-file
        path: ${{ steps.run-analysis.outputs.sarif }}