name: MSVC-Analysis

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  results: out/results

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Add MSVC to the PATH
      uses: lukka/run-vcpkg@v7
      with:
        setupOnly: true
        vcpkgGitCommitId: caea17de9196f8bd343efb496b1820e7438d1f83

    - name: Initialize MSVC Code Analysis
      uses: microsoft/msvc-code-analysis-action@main
      with:
        results: ${{ github.workspace }}
        ruleset: NativeRecommendedRules.ruleset

    - name: Build project
      run: msbuild MSBuildSolution.sln /p:Configuration=Release /p:Platform=x64 /t:rebuild

    - name: Upload SARIF results
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: ${{ github.workspace }}