name: MSVC-Analysis

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2
      with:
        vs-version: '[16.7,]'

    - name: Initialize MSVC Code Analysis
      uses: ./msvc-code-analysis-action
      with:
        sarif-output: out/results

    - name: Build project
      run: msbuild MSBuildSolution.sln /t:rebuild

    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: out/results
